# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0008_auto_20171230_0726'),
        ('foods', '0002_auto_20171230_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFoodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
            },
        ),
        migrations.AlterField(
            model_name='foods',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Calories:'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Carbohydrates'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fat'),
        ),
        migrations.AlterField(
            model_name='foods',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Protein'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Calories:'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Carbohydrates:'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fat:'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Protein:'),
        ),
        migrations.AddField(
            model_name='usersfoodhistory',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Breakfast', to='foods.Foods'),
        ),
        migrations.AddField(
            model_name='usersfoodhistory',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dinner', to='foods.Foods'),
        ),
        migrations.AddField(
            model_name='usersfoodhistory',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lunch', to='foods.Foods'),
        ),
        migrations.AddField(
            model_name='usersfoodhistory',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system_user.UserDescription'),
        ),
    ]
