# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20171230_0726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersfoodhistory',
            options={'verbose_name': "User's Food History", 'verbose_name_plural': "User's Food History"},
        ),
        migrations.AddField(
            model_name='usersfoodhistory',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
