# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20180101_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='userid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system_user.UserDescription'),
        ),
    ]
