# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20180101_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
