# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_diet_membership_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='membership_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Membership Value (Maximum is 1 and Lowest is 0)'),
        ),
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
