# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_auto_20180116_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietmembership', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Calories:')),
            ],
        ),
        migrations.RemoveField(
            model_name='diet',
            name='membership_value',
        ),
        migrations.AlterField(
            model_name='foods',
            name='diet',
            field=models.ManyToManyField(to='foods.DietMembership'),
        ),
        migrations.AddField(
            model_name='dietmembership',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Diet'),
        ),
    ]
