# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_auto_20180116_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Fiber'),
        ),
        migrations.AddField(
            model_name='foods',
            name='potassium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Potassium'),
        ),
        migrations.AddField(
            model_name='foods',
            name='sodium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Sodium'),
        ),
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
