# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_auto_20180121_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Breakfast', to='foods.Foods'),
        ),
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dinner', to='foods.Foods'),
        ),
        migrations.AlterField(
            model_name='usersfoodhistory',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lunch', to='foods.Foods'),
        ),
    ]
