# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebased', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='and_user_diet_is',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_user.Diet'),
        ),
    ]
