# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebased', '0003_auto_20180121_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_variable', models.CharField(default='', max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.DeleteModel(
            name='Rules',
        ),
    ]
