# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebased', '0004_auto_20180121_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('then_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Then Percentage')),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.AlterModelOptions(
            name='rulesmembership',
            options={'verbose_name': 'Rule Membership', 'verbose_name_plural': 'Rules Membership'},
        ),
        migrations.AddField(
            model_name='rules',
            name='and_user_sodium_requirement_is',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='and_user_sodium_requirement_is', to='knowledgebased.RulesMembership'),
        ),
        migrations.AddField(
            model_name='rules',
            name='if_food_sodium_content_is',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='if_food_sodium_content_is', to='knowledgebased.RulesMembership'),
        ),
    ]
