# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebased', '0005_auto_20180121_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='then_percentage',
            new_name='then_percentage_is',
        ),
    ]
