# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('percentage_above_basal', models.DecimalField(decimal_places=2, max_digits=3)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Physical Activity',
                'verbose_name_plural': 'Physical Activities',
            },
        ),
        migrations.CreateModel(
            name='UserDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('archived', models.BooleanField(default=False)),
                ('physical_activity_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='system_user.PhysicalActivity')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserSickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('archived', models.BooleanField(default=False)),
                ('user_sickness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sickness', to='system_user.UserDescription')),
            ],
            options={
                'verbose_name': 'Sickness',
                'verbose_name_plural': 'Sicknesses',
            },
        ),
    ]
