# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-22 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivity',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='percentage_above_basal',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userdescription',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userdescription',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
