# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-23 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0003_auto_20171222_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdescription',
            name='image',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/'),
        ),
    ]
