# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0006_auto_20171229_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdescription',
            name='sickness',
            field=models.ManyToManyField(blank=True, null=True, to='system_user.UserSickness'),
        ),
    ]
