# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0008_auto_20171230_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdescription',
            name='email',
        ),
        migrations.AddField(
            model_name='userdescription',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
