# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-05 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0017_auto_20180103_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdescription',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdescription',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdescription',
            name='password',
        ),
    ]
