# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-12 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0018_auto_20180105_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdescription',
            name='username',
        ),
        migrations.AlterField(
            model_name='userdescription',
            name='birthday',
            field=models.DateTimeField(verbose_name=datetime.date(2018, 1, 12)),
        ),
    ]
