# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 02:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0020_auto_20180113_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdescription',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2018, 1, 13, 2, 15, 17, 561785)),
        ),
    ]
