# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 02:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0021_auto_20180113_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdescription',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
