# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-13 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0022_auto_20180113_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdescription',
            name='birthday',
        ),
    ]
