# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0024_remove_userdescription_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Diet',
                'verbose_name_plural': 'Diets',
            },
        ),
        migrations.AddField(
            model_name='usersickness',
            name='diet',
            field=models.ManyToManyField(to='system_user.Diet'),
        ),
    ]
