# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_user', '0026_diet_membership_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='membership_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Membership Value (Maximum is 1 and Lowest is 0)'),
        ),
    ]
